sudo: required

services:
  - docker

branches:
  only:
    - master
    - develop

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=fijjas/uptmio-demo-repo
    - DOCKER_COMPOSE_VERSION=1.8.1

before_install:
  - echo Before-Install-OK
  - docker-compose up -d
  - docker ps
  - sleep 5

before_script:
  - echo Before-Script-OK

script:
  - docker-compose exec demo /opt/app/test

notifications:
  email: never
  slack:
    secure: "<TODO>"
